angular.module('AD',['ngRoute','AD-factories','AD-controllers','GE-factories'])
	.config(
		function($routeProvider){
		$routeProvider
		.when(
			'/home',
			{
				controller:'ADHomeController',
				templateUrl:'part/home.vw.html'
			}
		).when(
			'/productEdit',
			{
				controller:'ADProductsController',
				templateUrl:'part/productEdit.vw.html'
			}
		).when(
			'/products',
			{
				controller:'ADProductsController',
				templateUrl:'part/products.vw.html'
			}
		).when(
			'/clients',
			{
				controller:'ADClientsController',
				templateUrl:'part/clients.vw.html'
			}
		).when(
			'/promotionAdd',
			{
				controller:'ADPromotionsController',
				templateUrl:'part/promotionAdd.vw.html'
			}
		).when(
			'/promotionEdit',
			{
				controller:'ADPromotionsController',
				templateUrl:'part/promotionEdit.vw.html'
			}
		).when(
			'/promotions',
			{
				controller:'ADPromotionsController',
				templateUrl:'part/promotions.vw.html'
			}
		).when(
			'/orderDetails',
			{
				controller:'ADOrderDetailsController',
				templateUrl:'part/orderDetails.vw.html'
			}
		).when(
			'/orders',
			{
				controller:'ADOrdersController',
				templateUrl:'part/orders.vw.html'
			}
		).when(
			'/ordersByClient',
			{
				controller:'ADOrdersController',
				templateUrl:'part/ordersByClient.vw.html'
			}
		).otherwise(
			{
				redirectTo:'home'
			}
		);
	})
;