<?php
	session_start();
	require_once('../class/KeyGenerator.class.php');
	require_once('../class/NewManager.class.php');
	$response=array('data'=>0,'result'=>array());
	$attributes=array('clientId');
	$optional=array();
	$wrongData=array();
	$toAdd=array();
	foreach($attributes as $attr){
		if(empty($_POST[$attr])){
			if(!in_array($attr,$optional)){
				$wrongData[]=$attr;
			}
		}else{
			$toAdd[$attr]=$_POST[$attr];
		}
	}
	$response['result'][]=array('input-data-exists',empty($wrongData));
	if($wrongData){
		$response['data']++;
	}else{
		$key=KeyGenerator::generateKey();
		$result=NewManager::addElement(
			'log_session',
			array(
				'id'=>$key,
				'ip_address'=>$_SERVER['REMOTE_ADDR'],
				'client_id'=>$_POST['clientId'],
				'log_date'=>time()
			)
		);
		$response['result'][]=array('session-added',!empty($result));
		if(empty($result)){
			$response['data']++;
		}else{
			$result=KeyGenerator::starSelect(
				'log_session',
				array(
					'fields'=>array('id','ip_address','log_date'),
					'tables'=>array(
						'client'=>array(
							'fields'=>array('id','contact_name','contact_first_name','contact_email','contact_gsm','firm_name','firm_phone','firm_fax','suspended')
						)
					)
				),
				array(array('`log_session`.`id`',$key)),
				null
			);
			$response['result'][]=array('session-found',!empty($result));
			if(empty($result)){
				$response['data']++;
			}else{
				$response['data']=$result[0];
			}
		}
	}
	$response=newManager::toUTF8($response);
	echo json_encode($response);
?>