<?php
	session_start();
	require_once('../class/KeyGenerator.class.php');
	require_once('../class/NewManager.class.php');
	$response=array('data'=>0,'result'=>array());
	$attributes=array('contactEmail','firmName','firmPhone','contactGSM','firmFax','password');
	$alt=array('contactEmail','firmName','contactGSM','firmPhone','firmFax');
	$loginField='';
	$wrongData=array();
	foreach($attributes as $attr){
		if(in_array($attr,$alt)){
			if(!empty($_POST[$attr]) && empty($loginField)) {
				$loginField=$attr;
			}
		}else{
			if(empty($_POST[$attr])) {
				$wrongData[]=$attr;
			}
		}
	}
	$response['login_field']=$loginField;
	$response['result'][]=array('login-field-exists',!empty($loginField));
	if($loginField){
		$response['result'][]=array('input-data-exists',empty($wrongData));
		if($wrongData){
			$response['data']++;
		}else{
			$dataMeaning=array(
				'contactEmail'=>'contact_email',
				'contactGSM'=>'contact_gsm',
				'firmName'=>'firm_name',
				'firmPhone'=>'firm_phone',
				'firmFax'=>'firm_fax'
			);
			$result=NewManager::starSelect(
				'client',
				array(
					'fields'=>array(
						'id','contact_name','contact_first_name','contact_email','contact_gsm','firm_name','firm_phone','firm_fax'
					)
				),
				array(
					array('`client`.`'.$dataMeaning[$loginField].'`',$_POST[$loginField]),
					array('`client`.`password`',hash('sha256',$_POST['password']))
				),
				null
			);
			$response['result'][]=array('client-exists',!empty($result));
			if($result){
				$clientId=$result[0]['client_id'];
				$key=KeyGenerator::generateKey();
				$date=date('Y-m-d H:i:s');
				$result=NewManager::addElement(
					'log_session',
					array(
						'id'=>$key,
						'ip_address'=>$_SERVER['REMOTE_ADDR'],
						'client_id'=>$clientId,
						'log_date'=>$date
					)
				);
				$response['result'][]=array('session-added',!empty($result));
				if(empty($result)){
					$response['data']++;
				}else{
					$result=NewManager::starSelect(
						'log_session',
						array(
							'fields'=>array('id','ip_address','log_date'),
							'tables'=>array(
								'client'=>array(
									'fields'=>array('id','contact_name','contact_first_name','contact_email','contact_gsm','firm_name','firm_phone','firm_fax','suspended')
								)
							)
						),
						array(array('`log_session`.`id`',$key)),
						null
					);
					$response['result'][]=array('session-found',!empty($result));
					if(empty($result)){
						$response['data']++;
					}else{
						$response['data']=$result[0];
					}
				}
			}else{
				$response['data']++;
			}
		}
	}else{
		$response['data']++;
	}
	$response=newManager::toUTF8($response);
	echo json_encode($response);
?>