angular.module('FE',['ngRoute','FE-factories','FE-controllers','GE-factories'])
	.config(
	function($routeProvider){
		$routeProvider
		.when(
			'/home',
			{
				controller:'FEHomeController',
				templateUrl:'part/home.vw.html'
			}
		)/*.when(
			'/home/byebye',
			{
				controller:'FEHomeController',
				templateUrl:'part/homeByeBye.vw.html'
			}
		)*/.when(
			'/cardView',
			{
				controller:'FEShopController',
				templateUrl:'part/cardView.vw.html'
			}
		).when(
			'/cartConfirm',
			{
				controller:'FEShopController',
				templateUrl:'part/cartConfirm.vw.html'
			}
		).when(
			'/myOrders',
			{
				controller:'FEMyOrdersController',
				templateUrl:'part/myOrders.vw.html'
			}
		).when(
			'/myOrderDetails',
			{
				controller:'FEMyOrdersController',
				templateUrl:'part/myOrderDetails.vw.html'
			}
		).when(
			'/shop',
			{
				controller:'FEShopController',
				templateUrl:'part/shop.vw.html'
			}
		).when(
			'/order',
			{
				controller:'FEShopController',
				templateUrl:'part/order.vw.html'
			}
		).when(
			'/gallery',
			{
				controller:'FEGalleryController',
				templateUrl:'part/gallery.vw.html',
			}
		).when(
			'/photoGallery',
			{
				controller:'FEPhotoGalleryController',
				templateUrl:'part/photoGallery.vw.html'
			}
		).when(
			'/promotionAdverts',
			{
				controller:'FEPromotionAdvertController',
				templateUrl:'part/promotionAdverts.vw.html'
			}
		).when(
			'/promotions',
			{
				controller:'FEPromotionController',
				templateUrl:'part/promotions.vw.html'
			}
		).when(
			'/contact',
			{
				controller:'FEContactController',
				templateUrl:'part/contact-bis.vw.html'
			}
		).when(
			'/contactBis',
			{
				controller:'FEContactController',
				templateUrl:'part/contact-bis.vw.html'
			}
		).when(
			'/passwordChange',
			{
				controller:'FEPasswordChangeController',
				templateUrl:'part/passwordChange.vw.html'
			}
		).when(
			'/registration',
			{
				controller:'FERegistrationController',
				templateUrl:'part/registration.vw.html'
			}
		).when(
			'/userLog',
			{
				controller:'FEUserLogController',
				templateUrl:'part/userLog.vw.html'
			}
		).otherwise(
			{
				redirectTo:'/home'
			}
		);
	})
;
